### ISSUE TITLE
Bogus dynamic session limit complaints

### ISSUE THREAD

**Issue by KlavsKlavsen** [skyscrapers/monitoring-plugins#17]
Hi guys,
The haproxy-stats.pl check fails - rather often - on low-traffic backends like this:
Check haproxy CRITICAL - kki-prod-engagement-service:BACKEND sessions: 300.00%;
Because the stats looks like this:
stats: kki-prod-engagement-service-BACKEND=3;0;0;0;1
ie. it has 3 connections - and limit on "backend" is set to 1.

Thing is - the "limit" no. under 'backend' specificly is actually a dynamicly calculated limit - which is NOT enforced, unless minconn is set PER backend server and fullconn is set. see http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-fullconn
I see no way of seeing from the stats page if fullconn is set - which means you can't automaticly figure out if the limit is at all relevant.

I COULD - make it ignore "low numbers".. like limits below 500 or something..
or add an option for giving a "list of backend names that have dynamic limits enabled" - and then only enable $slim (the name used in the script) checking on those ?

**Comment by KlavsKlavsen** [comment]
or is anyone even using dynamic limits at all ?

**Comment by KlavsKlavsen** [comment]
For now I set it to ignore slim for BACKEND lines (as thats the one haproxy always sets - even if no limits is enforced):      
# Is session limit enforced?
-    if ($data[$slim]) {
+    if ($data[$slim] and $data[$svname] ne 'BACKEND') {

and this should mean we still get alerts if hardcoded maxconn limits (per backend) is close to being hit.

**Comment by iuriaranda** [comment]
Hi @KlavsKlavsen,

First of all I would like to apologise for not coming back to you in time.

We're now going over all the open issues and PRs of our open-source projects and doing some cleanup of stale items. I'm going to go ahead and close this issue for now. If this is still relevant for you feel free to reopen the issue or contribute a PR 🙂

We're making steps towards a more active community participation, so we'll do our best to respond to issues and PRs in a reasonable timeframe.

**Comment by WilliamDEdwards** [comment]
This is still relevant.
