### ISSUE TITLE
check_rabbitmq for queue count fails

### ISSUE THREAD

**Issue by georgeyord** [skyscrapers/monitoring-plugins#22]
...because of a new header in the response: 'name\tmessages'

A probable solution is described here: https://github.com/georgeyord/monitoring-plugins/pull/1/commits/f10e2bb72d7e2fe3661fc4f61a68a869ac982514

**Comment by iuriaranda** [comment]
Hi @georgeyord , could you elaborate a bit the problem you're having?

Also, could you submit that PR to our repo so we can integrate it as well?

Thank you very much for your contribution.

**Comment by georgeyord** [comment]
https://github.com/skyscrapers/monitoring-plugins/pull/23

**Comment by iuriaranda** [comment]
Closing this as #23 is merged now. Thanks
