### ISSUE TITLE
check_haproxy_stats.pl: perfdata and graphite/carbon

### ISSUE THREAD

**Issue by GerMalaz** [skyscrapers/monitoring-plugins#24]
hi, got this error in /var/log/graphite/console.log:

03/08/2019 23:55:24 :: Error parsing metric icinga2.lb1.services.haproxy_webfarm.haproxy-stats.perfdata.webfarm-www1=0;52428;58982;0;65536;webfarm-www2=0;52428;58982;0;65536;webfarm-www3=0;52428;58982;0;65536;webfarm-www4=0;52428;58982;0;65536;webfarm-BACKEND.max: Cannot parse path icinga2.lb1.services.haproxy_webfarm.haproxy-stats.perfdata.webfarm-www1=0;52428;58982;0;65536;webfarm-www2=0;52428;58982;0;65536;webfarm-www3=0;52428;58982;0;65536;webfarm-www4=0;52428;58982;0;65536;webfarm-BACKEND.max, invalid segment 52428

graphite expects the perfdata to be separated by spaces, like this: (just one proxy here):
Check haproxy CRITICAL - server: webfarm:www3 is MAINT; |webfarm-www1=3;52428;58982;0;65536; webfarm-www2=2;52428;58982;0;65536; webfarm-www3=0;52428;58982;0;65536; webfarm-www4=5;52428;58982;0;65536; webfarm-BACKEND=10;800;900;0;1000;

Thanks,
        Gerardo

**Comment by iuriaranda** [comment]
Hi @GerMalaz ,

We're not actively using that specific script at the moment, so I can't really test it nor reproduce your issue. Would you be willing to submit a PR for it?

Regarding what you mention, my only concern about changing the format to what graphite expects is that it might break other tools or integrations that expect the current format.

@KlavsKlavsen you being one of the last contributors to this script, what do you think about this?

**Comment by KlavsKlavsen** [comment]
@iuriaranda  We don't actually use the performance data part - as we get that directly via out collecter on the servers.. I wouldn't recommend anyone to to use that.. all monitoring that builds on statistics (collected in graphite/prometheus) - is being queried directly from our icinga.. and if that checks replaces a check on the servers - thats just a benefit.

**Comment by iuriaranda** [comment]
Due to the lack of activity on this issue, I'll go ahead and close it for now. @GerMalaz feel free to re-open it or open a new issue if you want to tackle this further.
